### ISSUE TITLE
Gulpfile contains unsupported functions

### ISSUE THREAD

**Issue by oparizek** [roihunter/roi-hunter-easy-woo-commerce-plugin#18]
The current version of `gulpfile.js` is not supported by Gulp 4. 
Example:
```
$ gulp -v
[13:26:03] CLI version 2.0.1
[13:26:03] Local version 4.0.0

$ gulp zip
[13:20:46] Using gulpfile /home/work/roi-hunter-easy-woo-commerce-plugin/gulpfile.js
[13:20:46] Starting 'zip'...
[13:20:46] 'zip' errored after 2.88 ms
[13:20:46] TypeError: gulp.start is not a function
    at /home/work/roi-hunter-easy-woo-commerce-plugin/gulpfile.js:92:10
    at taskWrapper (/home/work/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/home/work/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```

**Comment by oparizek** [comment]
Solved here: https://github.com/roihunter/roi-hunter-easy-woo-commerce-plugin/pull/32
